import Head from 'next/head';
import Image from 'next/image';
import { auth, signInWithGoogle } from '../firebase/firebase-config';
import { useRouter } from 'next/router';
import { NextRouter } from 'next/router';

export default function Home() {
  const isLoggedIn = auth.currentUser;

  const router = useRouter();

  if (isLoggedIn) {
    afterSignIn();
  }

  function afterSignIn() {
    router.push('/Days');
  }

  return (
    <div className="bg-surface text-onSurface h-screen w-screen flex items-center justify-center ">
      <Head>
        <title>Change the title of this page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>

      <SignInPage afterSignIn={afterSignIn} />
    </div>
  );
}

function SignInPage({ afterSignIn }: { afterSignIn: () => void }) {
  return (
    <>
      <main className="flex flex-col gap-8">
        <div>
          <h1 className="headline-lg">
            sinner
            <br />
            thoughts
          </h1>
          <p className="body-lg opacity-50">your personal journal</p>
        </div>
        <button
          onClick={async () => {
            await signInWithGoogle();
            if (auth.currentUser) {
              afterSignIn();
            }
          }}
          className="bg-blue-500 text-white rounded-md py-4 pr-8 pl-4 text-xl w-fit border-onSurface border-2 flex items-center  gap-4"
        >
          <figure className="mt-1">
            <Image src="/google-logo.svg" height={16} width={16} />
          </figure>
          <span className="label-lg">Sign in with Google</span>
        </button>
      </main>

      <footer className="absolute bottom-10">
        <button onClick={() => console.error('Connect this to Github')}>
          {'about >'}
        </button>
      </footer>
    </>
  );
}
